//! Stub parser for unp4k-extracted data directories.
//!
//! unp4k produces raw XML entity definitions rather than the JSON records
//! generated by scdatatools/StarFab. This parser is reserved for future
//! implementation.

use std::path::Path;

use anyhow::Result;

use crate::model::ParseResult;

/// Parser for directories extracted via unp4k.
pub struct Unp4kParser;

impl super::P4kParser for Unp4kParser {
    fn name(&self) -> &str {
        "unp4k"
    }

    fn detect(&self, path: &Path) -> bool {
        // unp4k produces raw XML records under entities/ or records/ but does
        // NOT have the DataCore JSON structure that scdatatools creates.
        let has_xml_records = path.join("entities").is_dir() || path.join("records").is_dir();
        let has_scdatatools = path.join("DataCore/libs/foundry/records").is_dir();
        has_xml_records && !has_scdatatools
    }

    fn parse(&self, _path: &Path, _version: &str) -> Result<ParseResult> {
        tracing::warn!("unp4k parser not yet implemented");
        Ok(ParseResult::new())
    }
}
